[package]
name = "erc6551crunch"
version = "0.1.1"
edition = "2021"

[dependencies]
alloy-primitives = { version = "0.7.6", features = ["rand"] }
fs4 = "0.8.4"
rayon = "1.0"
tiny-keccak = "2.0"
rustc-hash = "2.0.0"

[features]
default = []
asm = ["alloy-primitives/asm-keccak"]
